# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_prefs\RnD\tools\pw_scriptEditor\pw_multiScriptEditor\widgets\scriptEditor.ui'
#
# Created: Wed Apr 01 22:57:24 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCore, QtWidgets

class Ui_scriptEditor(object):
    def setupUi(self, scriptEditor):
        scriptEditor.setObjectName("scriptEditor")
        scriptEditor.resize(800, 609)
        self.centralwidget = QtWidgets.QWidget(scriptEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.executeAll_btn = QtWidgets.QPushButton(self.frame)
        self.executeAll_btn.setObjectName("executeAll_btn")
        self.horizontalLayout_2.addWidget(self.executeAll_btn)
        self.executeSel_btn = QtWidgets.QPushButton(self.frame)
        self.executeSel_btn.setObjectName("executeSel_btn")
        self.horizontalLayout_2.addWidget(self.executeSel_btn)
        self.clearHistory_btn = QtWidgets.QPushButton(self.frame)
        self.clearHistory_btn.setObjectName("clearHistory_btn")
        self.horizontalLayout_2.addWidget(self.clearHistory_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.out_ly = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.out_ly.setContentsMargins(0, 0, 0, 0)
        self.out_ly.setObjectName("out_ly")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.in_ly = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.in_ly.setContentsMargins(0, 0, 0, 0)
        self.in_ly.setObjectName("in_ly")
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.frame_2)
        scriptEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(scriptEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setTearOffEnabled(True)
        self.file_menu.setObjectName("file_menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setTearOffEnabled(True)
        self.help_menu.setObjectName("help_menu")
        self.tools_menu = QtWidgets.QMenu(self.menubar)
        self.tools_menu.setTearOffEnabled(True)
        self.tools_menu.setObjectName("tools_menu")
        self.options_menu = QtWidgets.QMenu(self.menubar)
        self.options_menu.setTearOffEnabled(True)
        self.options_menu.setObjectName("options_menu")
        self.theme_menu = QtWidgets.QMenu(self.options_menu)
        self.theme_menu.setTearOffEnabled(True)
        self.theme_menu.setObjectName("theme_menu")
        self.run_menu = QtWidgets.QMenu(self.menubar)
        self.run_menu.setTearOffEnabled(True)
        self.run_menu.setObjectName("run_menu")
        scriptEditor.setMenuBar(self.menubar)
        self.clearHistory_act = QtWidgets.QAction(scriptEditor)
        self.clearHistory_act.setObjectName("clearHistory_act")
        self.save_act = QtWidgets.QAction(scriptEditor)
        self.save_act.setObjectName("save_act")
        self.load_act = QtWidgets.QAction(scriptEditor)
        self.load_act.setObjectName("load_act")
        self.exit_act = QtWidgets.QAction(scriptEditor)
        self.exit_act.setObjectName("exit_act")
        self.openManual_act = QtWidgets.QAction(scriptEditor)
        self.openManual_act.setObjectName("openManual_act")
        self.quickHelp_act = QtWidgets.QAction(scriptEditor)
        self.quickHelp_act.setObjectName("quickHelp_act")
        self.saveSeccion_act = QtWidgets.QAction(scriptEditor)
        self.saveSeccion_act.setObjectName("saveSeccion_act")
        self.tabToSpaces_act = QtWidgets.QAction(scriptEditor)
        self.tabToSpaces_act.setObjectName("tabToSpaces_act")
        self.spacesToTabs_act = QtWidgets.QAction(scriptEditor)
        self.spacesToTabs_act.setObjectName("spacesToTabs_act")
        self.settingsFile_act = QtWidgets.QAction(scriptEditor)
        self.settingsFile_act.setObjectName("settingsFile_act")
        self.editTheme_act = QtWidgets.QAction(scriptEditor)
        self.editTheme_act.setObjectName("editTheme_act")
        self.shortcuts_act = QtWidgets.QAction(scriptEditor)
        self.shortcuts_act.setObjectName("shortcuts_act")
        self.donate_act = QtWidgets.QAction(scriptEditor)
        self.donate_act.setObjectName("donate_act")
        self.about_act = QtWidgets.QAction(scriptEditor)
        self.about_act.setObjectName("about_act")
        self.execAll_act = QtWidgets.QAction(scriptEditor)
        self.execAll_act.setObjectName("execAll_act")
        self.execSel_act = QtWidgets.QAction(scriptEditor)
        self.execSel_act.setObjectName("execSel_act")
        self.copy_act = QtWidgets.QAction(scriptEditor)
        self.copy_act.setObjectName("copy_act")
        self.cut_act = QtWidgets.QAction(scriptEditor)
        self.cut_act.setObjectName("cut_act")
        self.paste_act = QtWidgets.QAction(scriptEditor)
        self.paste_act.setObjectName("paste_act")
        self.find_act = QtWidgets.QAction(scriptEditor)
        self.find_act.setObjectName("find_act")
        self.undo_act = QtWidgets.QAction(scriptEditor)
        self.undo_act.setObjectName("undo_act")
        self.redo_act = QtWidgets.QAction(scriptEditor)
        self.redo_act.setObjectName("redo_act")
        self.printHelp_act = QtWidgets.QAction(scriptEditor)
        self.printHelp_act.setObjectName("printHelp_act")
        self.comment_cat = QtWidgets.QAction(scriptEditor)
        self.comment_cat.setObjectName("comment_cat")
        self.file_menu.addAction(self.saveSeccion_act)
        self.file_menu.addAction(self.save_act)
        self.file_menu.addAction(self.load_act)
        self.help_menu.addAction(self.openManual_act)
        self.help_menu.addAction(self.shortcuts_act)
        self.help_menu.addAction(self.donate_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.printHelp_act)
        self.help_menu.addAction(self.about_act)
        self.tools_menu.addAction(self.undo_act)
        self.tools_menu.addAction(self.redo_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.copy_act)
        self.tools_menu.addAction(self.cut_act)
        self.tools_menu.addAction(self.paste_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.tabToSpaces_act)
        self.tools_menu.addAction(self.comment_cat)
        self.tools_menu.addAction(self.find_act)
        self.theme_menu.addAction(self.editTheme_act)
        self.theme_menu.addSeparator()
        self.options_menu.addAction(self.theme_menu.menuAction())
        self.options_menu.addAction(self.settingsFile_act)
        self.run_menu.addAction(self.execAll_act)
        self.run_menu.addAction(self.execSel_act)
        self.run_menu.addAction(self.clearHistory_act)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.tools_menu.menuAction())
        self.menubar.addAction(self.run_menu.menuAction())
        self.menubar.addAction(self.options_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(scriptEditor)
        QtCore.QMetaObject.connectSlotsByName(scriptEditor)

    def retranslateUi(self, scriptEditor):
        scriptEditor.setWindowTitle(QtWidgets.QApplication.translate("scriptEditor", "MainWindow", None))
        self.executeAll_btn.setToolTip(QtWidgets.QApplication.translate("scriptEditor", "Execute all code in current tab\n"
"", None))
        self.executeAll_btn.setText(QtWidgets.QApplication.translate("scriptEditor", "Execute All", None))
        self.executeSel_btn.setToolTip(QtWidgets.QApplication.translate("scriptEditor", "Execute selected code in current tab\n"
"", None))
        self.executeSel_btn.setText(QtWidgets.QApplication.translate("scriptEditor", "Execute Selected", None))
        self.clearHistory_btn.setToolTip(QtWidgets.QApplication.translate("scriptEditor", "Clear output window", None))
        self.clearHistory_btn.setText(QtWidgets.QApplication.translate("scriptEditor", "Clear", None))
        self.file_menu.setTitle(QtWidgets.QApplication.translate("scriptEditor", "File", None))
        self.help_menu.setTitle(QtWidgets.QApplication.translate("scriptEditor", "Help", None))
        self.tools_menu.setTitle(QtWidgets.QApplication.translate("scriptEditor", "Edit", None))
        self.options_menu.setTitle(QtWidgets.QApplication.translate("scriptEditor", "Options", None))
        self.theme_menu.setTitle(QtWidgets.QApplication.translate("scriptEditor", "Theme", None))
        self.run_menu.setTitle(QtWidgets.QApplication.translate("scriptEditor", "Run", None))
        self.clearHistory_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Clear Output", None))
        self.save_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Save Script", None))
        self.load_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Load Script", None))
        self.exit_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Exit", None))
        self.openManual_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Manual", None))
        self.quickHelp_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Quick Help", None))
        self.saveSeccion_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Save session", None))
        self.tabToSpaces_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Tab to spaces", None))
        self.spacesToTabs_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Spaces to tab", None))
        self.settingsFile_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Open Settings Folder", None))
        self.editTheme_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Edit ...", None))
        self.shortcuts_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Show Shortcuts", None))
        self.donate_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Donate", None))
        self.about_act.setText(QtWidgets.QApplication.translate("scriptEditor", "About", None))
        self.execAll_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Execute All", None))
        self.execSel_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Execute Selected", None))
        self.copy_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Copy", None))
        self.cut_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Cut", None))
        self.paste_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Paste", None))
        self.find_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Find and Replace", None))
        self.undo_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Undo", None))
        self.redo_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Redo", None))
        self.printHelp_act.setText(QtWidgets.QApplication.translate("scriptEditor", "Print Help", None))
        self.comment_cat.setText(QtWidgets.QApplication.translate("scriptEditor", "Comment", None))

